"""initial

Revision ID: 5cee931e3ae7
Revises: 
Create Date: 2025-01-12 00:14:22.162256

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5cee931e3ae7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conferences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_conferences_name"), "conferences", ["name"], unique=True)
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "themes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("bg_color", sa.Text(), nullable=False),
        sa.Column("bg_secondary_color", sa.Text(), nullable=False),
        sa.Column("color_primary", sa.Text(), nullable=False),
        sa.Column("color_lightGrey", sa.Text(), nullable=False),
        sa.Column("color_grey", sa.Text(), nullable=False),
        sa.Column("color_darkGrey", sa.Text(), nullable=False),
        sa.Column("color_error", sa.Text(), nullable=False),
        sa.Column("color_success", sa.Text(), nullable=False),
        sa.Column("grid_maxWidth", sa.Text(), nullable=False),
        sa.Column("grid_gutter", sa.Text(), nullable=False),
        sa.Column("font_size", sa.Text(), nullable=False),
        sa.Column("font_color", sa.Text(), nullable=False),
        sa.Column("font_family_sans", sa.Text(), nullable=False),
        sa.Column("font_family_mono", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("password", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("admin", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "days",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("conference", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["conference"], ["conferences.id"], name="fk_days_conferences_id_conference"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rooms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("conference", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["conference"],
            ["conferences.id"],
            name="fk_rooms_conferences_id_conference",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rooms_name"), "rooms", ["name"], unique=False)
    op.create_table(
        "users_roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("role", sa.Integer(), nullable=True),
        sa.Column("user", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["role"],
            ["roles.id"],
            name="fk_users_roles_roles_role_id",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user"],
            ["users.id"],
            name="fk_users_roles_users_user_id",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "presentations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("user", sa.Integer(), nullable=True),
        sa.Column("start", sa.DateTime(), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("day", sa.Integer(), nullable=True),
        sa.Column("room", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["day"], ["days.id"], name="fk_presentations_days_id_day"
        ),
        sa.ForeignKeyConstraint(
            ["room"], ["rooms.id"], name="fk_presentations_rooms_id_room"
        ),
        sa.ForeignKeyConstraint(
            ["user"], ["users.id"], name="fk_presentations_users_id_user"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("presentations")
    op.drop_table("users_roles")
    op.drop_index(op.f("ix_rooms_name"), table_name="rooms")
    op.drop_table("rooms")
    op.drop_table("days")
    op.drop_table("users")
    op.drop_table("themes")
    op.drop_table("roles")
    op.drop_index(op.f("ix_conferences_name"), table_name="conferences")
    op.drop_table("conferences")
    # ### end Alembic commands ###
